name: Secret Test

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Echo GitHub Secret
      run: | 
        sudo su
        whoami
        sudo apt-get update
        echo "The Secret Is ${{ secrets.TEST_SECRET }}"
        python3 ./build_tools/test-secret-equivilent.py ${{ secrets.TEST_SECRET }}
        sudo curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        sudo sudo dpkg -i packages-microsoft-prod.deb
        sudo rm packages-microsoft-prod.deb
        sudo apt-get update && sudo apt-get install -y fuse3 blobfuse2
        sudo chmod +x ./build_tools/install_ccache.sh
        sudo ./build_tools/install_ccache.sh "4.10.2"
        sudo mkdir -p /mnt/azureblob
        sudo blobfuse2 mount --allow-other --config-file=./build_tools/fuse_connection.yaml /mnt/azureblob/
        echo "DONE"
        
