name: Secret Test

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Echo GitHub Secret
      run: | 
        echo ${{ secrets.TEST_SECRET }}
